[package]
name = "deltasigma"
version = "0.1.0"
authors = ["Noah Hüsser <yatekii@yatekii.ch>"]
edition = "2018"

[lib]
crate_type = ["cdylib"]

[dependencies]
jni = "0.13.1"
ndarray = "*"
num = "*"
ndarray-linalg = "*"
log = "*"
itertools = "*"